name: CI

on:
  push:
    branches:  
    - master
    - dev  
  pull_request:
    branches:  
    - master
    - dev  
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
    inputs:
      name:
        description: 'Trigger CI'
        required: true
        default: 'Mona the Octocat'
   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
